### ISSUE TITLE
Office 365 response received but no "RequestedSecurityToken"

### ISSUE THREAD

**Issue by kgmccann** [LukasK13/sharepointr#1]
https://github.com/LukasK13/sharepointr/blob/11bdffd457b99f5c06d1bcf4f5b4b0176fbdba1c/R/sharepoint_driver.R#L46

Thank you for putting all this together, but I am not having success with the Office365 version.  I stepped through sp_connection() and the problem comes at line 46, where content$Envelope$Body$RequestSecurityTokenResponse$RequestedSecurityToken does not exist in the response I am getting from Sharepoint Online.   The only elements there are $AppliesTo and $pp .

**Comment by LukasK13** [comment]
The missing `RequestedSecurityToken` means, that something is wrong with your request.
Can you provide the exact content of the response? Of course made anonymous.
Just to make sure: did you use an adress like `mydomain.sharepoint.com` and your microsoft email address as username?

**Comment by kgmccann** [comment]
I was using my MS email address as username, but I do not have access to the main sharepoint. In my test case, I was trying to access an address like: `mydomain.sharepoint.com/sites/mysite` but in another use-case I only currently have access to a single list: `mydomain.sharepoint.com/sites/mysite/subsite/Lists/SpecificList`.  
Perhaps this is simply beyond the package's scope at the moment?

**Comment by LukasK13** [comment]
No, it's a bug in the function `sp_connection()`. As shown [here](https://paulryan.com.au/2014/spo-remote-authentication-rest/) the root address to your Sharepoint instance needs to be provided in the request. Therefore the root address is now extracted from the provided address string.
In detail, use
`sp_con <- sp_connection(Address = "mydomain.sharepoint.com/sites/mysite", Username = "yourOffice365email@you.com", Password = "YourOffice365Password")`
for requesting the authentication cookies and
`sp_list <- sp_list(sp_con, "YourList")`

In order to get this to work, you need to reinstall the package  `sharepointr`.
I hope this solves your problem.
